export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST'  // Загрузка ингредиентов
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED'  // Ошибка ингредиентов
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS'  // Получение ингредиентов

export const CHOOSE_INGREDIENTS: 'CHOOSE_INGREDIENTS' = 'CHOOSE_INGREDIENTS' // Выбор ингредиентов

export const INCREASE_COUNTER: 'INCREASE_COUNTER' = 'INCREASE_COUNTER' // Увеличение счетчика
export const DECREASE_COUNTER: 'DECREASE_COUNTER' = 'DECREASE_COUNTER' // Уменьшение счетчика
export const DELETE_INGREDIENT: 'DELETE_INGREDIENT' = 'DELETE_INGREDIENT'  // Удаление ингредиента
export const MOVE_INGREDIENT: 'MOVE_INGREDIENT' = 'MOVE_INGREDIENT' // Сортировка ингредиентов

export const CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST' = 'CREATE_ORDER_REQUEST' // Успешно созданный заказ
export const CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS' = 'CREATE_ORDER_SUCCESS' // Запрос создания заказов
export const CREATE_ORDER_FAILED: 'CREATE_ORDER_FAILED' = 'CREATE_ORDER_FAILED' // Ошибка запроса создания заказа

export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST' // Запрос заказа
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS' // Успешно
export const GET_ORDER_FAILED: 'GET_ORDER_FAILED' = 'GET_ORDER_FAILED' // Ошибка

export const GET_USER_ORDER_REQUEST: 'GET_USER_ORDER_REQUEST' = 'GET_USER_ORDER_REQUEST' // Запрос пользовательских заказов
export const GET_USER_ORDER_SUCCESS: 'GET_USER_ORDER_SUCCESS' = 'GET_USER_ORDER_SUCCESS' // Успех
export const GET_USER_ORDER_FAILED: 'GET_USER_ORDER_FAILED' = 'GET_USER_ORDER_FAILED' // Ошибка