export const REGISTER_REQUEST: 'REGISTER_REQUEST' = 'REGISTER_REQUEST' // Запрос регистрации
export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS' // Удачно
export const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED' // Ошибка

export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST' // Запрос авторизации
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS' // Удачно
export const LOGIN_FAILED: 'LOGIN_FAILED' = 'LOGIN_FAILED' // Ошибка

export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST' // Запрос инфо о пользователе
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS' // Удачно
export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED' // Ошибка

export const UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST' = 'UPDATE_USER_REQUEST' // Запрос обновления инфо о пользователе
export const UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS' = 'UPDATE_USER_SUCCESS' // Удачно
export const UPDATE_USER_FAILED: 'UPDATE_USER_FAILED' = 'UPDATE_USER_FAILED' // Ошибка

export const FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST' = 'FORGOT_PASSWORD_REQUEST' // Запрос "забыл пароль"
export const FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS' = 'FORGOT_PASSWORD_SUCCESS' // Удачно
export const FORGOT_PASSWORD_FAILED: 'FORGOT_PASSWORD_FAILED' = 'FORGOT_PASSWORD_FAILED' // Ошибка

export const RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST' = 'RESET_PASSWORD_REQUEST' // Запрос смена пароля
export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS' // Удачно
export const RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED' = 'RESET_PASSWORD_FAILED' // Ошибка

export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST' // Запрос "выход"
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS' // Удачно
export const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED' // Ошибка

export const REFRESH_TOKEN_REQUEST: 'REFRESH_TOKEN_REQUEST' = 'REFRESH_TOKEN_REQUEST' // Запрос обновление токена
export const REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS' = 'REFRESH_TOKEN_SUCCESS' // Удачно
export const REFRESH_TOKEN_FAILED: 'REFRESH_TOKEN_FAILED' = 'REFRESH_TOKEN_FAILED' // Ошибка
